// tools/protoc-gen-go-http/main.go
package main

import (
	"bytes"
	"fmt"
	"path"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_http.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	pkg := string(file.GoPackageName)
	g.P("// Code generated by protoc-gen-go-http. DO NOT EDIT.")
	g.P()
	g.P("package ", pkg)
	g.P()
	g.P("import (")
	g.P(`  "context"`)
	g.P(`  "google.golang.org/protobuf/proto"`)
	g.P(`  "github.com/your/module/internal/transport/http"`)
	g.P(")")
	g.P()

	for _, svc := range file.Services {
		genService(g, svc)
	}
}

func genService(g *protogen.GeneratedFile, svc *protogen.Service) {
	svcName := svc.GoName // e.g., Greeter
	serverIface := fmt.Sprintf("%sHTTPServer", svcName)
	// Interface
	g.P("// ", serverIface, " is the server API for ", svcName, " service (http transport).")
	g.P("type ", serverIface, " interface {")
	for _, m := range svc.Methods {
		req := m.Input.GoIdent.GoName
		resp := m.Output.GoIdent.GoName
		g.P(fmt.Sprintf("  %s(ctx context.Context, req *%s) (*%s, error)", m.GoName, req, resp))
	}
	g.P("}")
	g.P()

	// Generate Method wrappers and ServiceDesc
	descName := fmt.Sprintf("%s_Http_ServiceDesc", svcName)
	g.P("var ", descName, " = &http.ServiceDesc{")
	g.P(`  ServiceName: "` + svc.FullName + `",`)
	g.P("  HandlerType: (*" + serverIface + ")(nil),")
	g.P("  Methods: []http.MethodDesc{")
	ops := 1
	for _, m := range svc.Methods {
		handlerName := fmt.Sprintf("_%s_%s_Http_Handler", svcName, m.GoName)
		g.P("    {")
		g.P(fmt.Sprintf("      MethodName: \"%s\",", m.GoName))
		g.P(fmt.Sprintf("      Handler: %s,", handlerName))
		g.P(fmt.Sprintf("      Ops: %d,", ops))
		g.P("    },")
		ops++
	}
	g.P("  },")
	g.P("}")
	g.P()

	// Register function
	g.P("func Register", svcName, "HTTPServer(s *http.Server, srv ", serverIface, ") {")
	g.P("  s.RegisterService(", descName, ", srv)")
	g.P("}")
	g.P()

	// Handlers
	ops = 1
	for _, m := range svc.Methods {
		handlerName := fmt.Sprintf("_%s_%s_Http_Handler", svcName, m.GoName)
		inType := m.Input.GoIdent.GoName
		outType := m.Output.GoIdent.GoName

		g.P("func ", handlerName, "(srv interface{}, ctx context.Context, data []byte) ([]byte, error) {")
		g.P("  in := new(", inType, ")")
		g.P("  if err := proto.Unmarshal(data, in); err != nil {")
		g.P("    return nil, err")
		g.P("  }")
		g.P("  // call actual impl")
		g.P("  resp, err := srv.(", serverIface, ").", m.GoName, "(ctx, in)")
		g.P("  if err != nil || resp == nil {")
		g.P("    return nil, err")
		g.P("  }")
		g.P("  outb, err := proto.Marshal(resp)")
		g.P("  if err != nil { return nil, err }")
		g.P("  return outb, nil")
		g.P("}")
		g.P()
		ops++
	}
}
