//// Code generated by protoc-gen-go-websocket. DO NOT EDIT.
//// versions:
//// - protoc-gen-go-websocket v2.8.6
//// - protoc            v3.6.1
//// source: metadata/metadata.proto
//
//package metadata
//
//// This is a compile-time assertion to ensure that this generated file
//// is compatible with the wise package it is being compiled against.
//import (
//	"context"
//
//	"git.dzz.com/egame/wise/library/work"
//	"git.dzz.com/egame/wise/transport/websocket"
//
//	"google.golang.org/grpc/codes"
//	"google.golang.org/grpc/status"
//	"google.golang.org/protobuf/proto"
//)
//
//// MetadataWebsocketServer is the server API for Metadata service.
//type MetadataWebsocketServer interface {
//	GetLoop() work.ITaskLoop
//	OnSessionOpen(*websocket.Session)
//	OnSessionClose(*websocket.Session)
//	ListServices(context.Context, *ListServicesRequest) (*ListServicesReply, error)
//	GetServiceDesc(context.Context, *GetServiceDescRequest) (*GetServiceDescReply, error)
//}
//
//func RegisterMetadataWebsocketServer(s *websocket.Server, srv MetadataWebsocketServer) {
//	s.RegisterService(&Metadata_Websocket_ServiceDesc, srv, srv.OnSessionOpen, srv.OnSessionClose)
//}
//
//func _Metadata_ListServices_Websocket_Handler(srv interface{}, ctx context.Context, data []byte, interceptor websocket.UnaryServerInterceptor) ([]byte, error) {
//	in := new(ListServicesRequest)
//	if err := proto.Unmarshal(data, in); err != nil {
//		return nil, err
//	}
//	doFunc := func(ctx context.Context, req *ListServicesRequest) ([]byte, error) {
//		doRequest := func() ([]byte, error) {
//			resp, err := srv.(MetadataWebsocketServer).ListServices(ctx, req)
//			if err != nil || resp == nil {
//				return nil, err
//			}
//			return proto.Marshal(resp)
//		}
//		if loop := srv.(MetadataWebsocketServer).GetLoop(); loop != nil {
//			return loop.PostAndWaitCtx(ctx, doRequest)
//		}
//		return doRequest()
//	}
//	if interceptor == nil {
//		return doFunc(ctx, in)
//	}
//	info := &websocket.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/wise.api.Metadata/ListServices",
//	}
//	handler := func(ctx context.Context, req interface{}) ([]byte, error) {
//		r, ok := req.(*ListServicesRequest)
//		if !ok {
//			return nil, status.Errorf(codes.InvalidArgument, "Invalid Request Argument, expect: *ListServicesRequest, Not: %T", req)
//		}
//		return doFunc(ctx, r)
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//func _Metadata_GetServiceDesc_Websocket_Handler(srv interface{}, ctx context.Context, data []byte, interceptor websocket.UnaryServerInterceptor) ([]byte, error) {
//	in := new(GetServiceDescRequest)
//	if err := proto.Unmarshal(data, in); err != nil {
//		return nil, err
//	}
//	doFunc := func(ctx context.Context, req *GetServiceDescRequest) ([]byte, error) {
//		doRequest := func() ([]byte, error) {
//			resp, err := srv.(MetadataWebsocketServer).GetServiceDesc(ctx, req)
//			if err != nil || resp == nil {
//				return nil, err
//			}
//			return proto.Marshal(resp)
//		}
//		if loop := srv.(MetadataWebsocketServer).GetLoop(); loop != nil {
//			return loop.PostAndWaitCtx(ctx, doRequest)
//		}
//		return doRequest()
//	}
//	if interceptor == nil {
//		return doFunc(ctx, in)
//	}
//	info := &websocket.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/wise.api.Metadata/GetServiceDesc",
//	}
//	handler := func(ctx context.Context, req interface{}) ([]byte, error) {
//		r, ok := req.(*GetServiceDescRequest)
//		if !ok {
//			return nil, status.Errorf(codes.InvalidArgument, "Invalid Request Argument, expect: *GetServiceDescRequest, Not: %T", req)
//		}
//		return doFunc(ctx, r)
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//var Metadata_Websocket_ServiceDesc = websocket.ServiceDesc{
//	ServiceName: "wise.api.Metadata",
//	HandlerType: (*MetadataWebsocketServer)(nil),
//	Methods: []websocket.MethodDesc{
//		{
//			MethodName: "ListServices",
//			Handler:    _Metadata_ListServices_Websocket_Handler,
//			Ops:        1001,
//		},
//		{
//			MethodName: "GetServiceDesc",
//			Handler:    _Metadata_GetServiceDesc_Websocket_Handler,
//			Ops:        1003,
//		},
//	},
//}

package metadata
